name: bwu_log
version: 0.1.1
authors:
  - Günter Zöchbauer <guenter@gzoechbauer.com>
  - Adam Bender <bendera@google.com>
description: A logging utility for Dart (fork of quiver-log)
homepage: https://github.com/bwu-dart/bwu-log
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  intl: '^0.12.7'
  logging: '^0.11.0'
  path: '^1.1.0'
dev_dependencies:
  bwu_grinder_tasks: '^0.1.0-dev'
  grinder: '^0.8.0+2'
  mock: '^0.12.0'
  test: '^0.12.0'
