name: bwu_log
version: 1.0.3
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Adam Bender <bendera@google.com>
description: A logging utility for Dart
homepage: https://github.com/bwu-dart/bwu_log
environment:
  sdk: '>=1.9.0'

dependencies:
  intl: ^0.12.3
  logging: ^0.11.0
  path: '^1.3.5'

dev_dependencies:
  bwu_utils_dev: ^0.1.0-dev.9
  mock: ^0.12.0
  test: ^0.12.0

transformers:
- $dart2js:
    $exclude: bin
