name: bwu_log
version: 1.0.3
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Adam Bender <bendera@google.com>
description: A logging utility for Dart
homepage: https://github.com/bwu-dart/bwu_log
environment:
  sdk: '>=1.9.0'
dependencies:
  intl: ^0.12.3
  logging: ^0.11.0
  path: ^1.1.0
  polymer: ^0.16.3+2

dev_dependencies:
  mock: ^0.12.0-beta.0
  test: ^0.12.0
  grinder: ^0.7.0

dependency_overrides:
  logging: ^0.11.0
